### ISSUE TITLE
Upgrade to change the brightness from HA

### ISSUE THREAD

**Issue by casamarbar** [airy10/esphome-m5stickC#19]
Thanks for your job
It would be possible to add a sensor to be able to change the brightness from HA of the screen?

**Comment by c99koder** [comment]
Create an input_number helper entity in Home Assistant called lcd_brightness that stores a value between 0 and 100, and then add the following to your esphome config to set the backlight level when the value changes:

```yaml
sensor:
  - platform: axp192
    id: backlight
    …

  - platform: homeassistant
    id: brightness
    entity_id: input_number.lcd_brightness
    internal: true
    on_value:
      then:
        lambda: |-
          id(backlight).set_brightness(id(brightness).state/100.0);
          id(backlight).update();
```
